name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16

      - name: install and build
        run: |
          yarn install
          yarn build

      - name: deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          rsync -r -a -v -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" --delete ./ $EC2_USER@$EC2_HOST:~/stylehub
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "
            source ~/.bashrc;
            cd ~/stylehub; 
            /home/ubuntu/.nvm/versions/node/v18.16.0/bin/yarn install;
            /home/ubuntu/.nvm/versions/node/v18.16.0/bin/pm2 delete stylehub; 
            /home/ubuntu/.nvm/versions/node/v18.16.0/bin/pm2 start 'yarn start -p 8000' --name stylehub;
          "
          rm -f private_key.pem
